# Generated by Django 5.2.7 on 2025-11-05 15:00

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import reldigital.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('dui', models.CharField(max_length=20, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.TextField()),
                ('phone', models.TextField(blank=True, default=None, max_length=150, null=True)),
                ('extra_emails', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='reldigital_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='reldigital_users_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'releng_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'Plant'), (2, 'Area'), (3, 'Equipment')], default=1)),
                ('attachment', models.FileField(null=True, upload_to=reldigital.models.get_upload_entity)),
                ('extra_info', models.JSONField(default=list)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reldigital.entity')),
            ],
            options={
                'db_table': 'releng_entities',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Abierto'), (2, 'Cerrado')], default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('attachment', models.FileField(null=True, upload_to=reldigital.models.get_upload_reports)),
                ('program', models.IntegerField(choices=[(1, 'Programado'), (2, 'No programado')], default=1)),
                ('task_type', models.IntegerField(choices=[(1, 'PDM'), (2, 'NDT'), (3, 'AL'), (4, 'IV')], default=1)),
                ('execution_status', models.IntegerField(choices=[(1, 'Ejecutado'), (2, 'No ejecutado')], default=1)),
                ('observations', models.TextField(null=True)),
                ('condition', models.IntegerField(choices=[(1, 'Normal'), (2, 'Tolerable'), (3, 'Precaución'), (4, 'Crítico')], default=1)),
                ('diagnostic', models.TextField(null=True)),
                ('recomendations', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reldigital.entity')),
            ],
            options={
                'db_table': 'releng_reports',
            },
        ),
    ]
