# Generated by Django 5.2.7 on 2025-11-05 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='comment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='ot_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='ot_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='ot_status',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'Cerrado')], default=1),
        ),
        migrations.AddField(
            model_name='notice',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='reldigital.report'),
        ),
        migrations.AddField(
            model_name='notice',
            name='status_real',
            field=models.IntegerField(choices=[(1, 'Atendido'), (2, 'No entendido')], default=1),
        ),
    ]
