# Generated by Django 5.2.7 on 2025-11-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0002_notice_comment_notice_ot_date_notice_ot_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='extra_info',
            field=models.JSONField(default=list, null=True),
        ),
    ]
