# Generated by Django 5.2.7 on 2025-11-05 15:48

import reldigital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0003_alter_entity_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=reldigital.models.get_upload_entity),
        ),
        migrations.AlterField(
            model_name='entity',
            name='extra_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
