# Generated by Django 5.2.7 on 2025-11-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0004_alter_entity_attachment_alter_entity_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='recomendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
