# Generated by Django 5.2.7 on 2025-11-05 16:07

import reldigital.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0005_alter_report_diagnostic_alter_report_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=reldigital.models.get_upload_reports),
        ),
    ]
