# Generated by Django 5.2.7 on 2025-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0006_alter_report_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='ot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='ot_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
