# Generated by Django 5.2.7 on 2025-11-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0007_alter_notice_comment_alter_notice_ot_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='execution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
