# Generated by Django 5.2.8 on 2025-11-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0009_alter_report_name_noticeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='service_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
