# Generated by Django 5.2.8 on 2026-02-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0010_report_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.IntegerField(choices=[(1, 'Plant'), (2, 'Area'), (3, 'Equipment'), (4, 'Component'), (5, 'Subcomponent')], default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='task_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
