# Generated by Django 5.2.8 on 2026-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0011_entity_tag_alter_entity_extra_info_alter_entity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['entity', 'is_active'], name='releng_repo_entity__9041ae_idx'),
        ),
    ]
