# Generated by Django 5.2.8 on 2026-02-22 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0012_report_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table='releng_notices',
        ),
        migrations.AlterModelTable(
            name='noticeimage',
            table='releng_notice_images',
        ),
    ]
