# Generated by Django 5.2.8 on 2026-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reldigital', '0013_alter_notice_table_alter_noticeimage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='task_type',
        ),
        migrations.AddField(
            model_name='report',
            name='work_type',
            field=models.IntegerField(choices=[(1, 'PDM'), (2, 'NDT')], default=1),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.IntegerField(choices=[(1, 'Plant'), (2, 'Area'), (3, 'Route'), (4, 'Equipment'), (5, 'Item'), (6, 'Component')], default=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='status_real',
            field=models.IntegerField(choices=[(1, 'Atendido'), (2, 'No antendido')], default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='service_type',
            field=models.IntegerField(choices=[(1, 'Vibraciones y temperatura'), (2, 'Alineamiento de ejes'), (3, 'Termografía infrarroja'), (4, 'Ultrasonido convencional'), (5, 'Tintes Penetrantes'), (6, 'Ultrasonido avanzado'), (7, 'Metrología'), (8, 'Inspección visual'), (9, 'Otros')], default=1),
        ),
    ]
